# -*- mode: ruby -*-
# vi: set ft=ruby :

home = ENV['HOME']

MACHINES = {
	:centos_host => {
		:box_name => "centos/7",
		:ip_addr => '172.16.1.1',
		:hname => 'centos-host',
		:memory => 256
	},
	:kalilinux_host => {
		:box_name => "kalilinux/rolling",
		:ip_addr => '172.16.1.2',
		:hname => 'kali-host',
		:memory => 256
	}
}

Vagrant.configure("2") do |config|
	MACHINES.each do |boxname, boxconfig|
		config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name=boxconfig[:hname]
			box.vm.network "private_network", ip: boxconfig[:ip_addr]
			box.vm.provider :virtualbox do |vb|
				vb.customize ["modifyvm",:id,"--memory",boxconfig[:memory]]
				vb.cpus =2
				vb.gui=false
			end
		end
	end
end